CREATE TABLE MOVIE (
TITLE TEXT,
YEAR_OF_RELEASE DATE,
PLOT_OUTLINE TEXT,
LENGTH_ INTEGER, 
PRIMARY KEY (TITLE, YEAR_OF_RELEASE)
);

CREATE TABLE PRODUCTION_COMPANY (
COMP_NAME TEXT PRIMARY KEY,
ADDRESS TEXT
);


CREATE TABLE PRODUCTED_BY (
MOVIE_TITLE TEXT,
YEAR_OF_RELEASE DATE,
COMP_NAME TEXT,
CONSTRAINT PRODUCTED
	FOREIGN KEY (MOVIE_TITLE, YEAR_OF_RELEASE)
REFERENCES MOVIE (TITLE, YEAR_OF_RELEASE),
FOREIGN KEY (COMP_NAME)
REFERENCES PRODUCTION_COMPANY (COMP_NAME),
PRIMARY KEY
(MOVIE_TITLE, YEAR_OF_RELEASE)
);

CREATE TABLE GENRE (
GEN_NAME TEXT PRIMARY KEY
);

CREATE TABLE HAS_GENRE (
MOVIE_TITLE TEXT,
YEAR_OF_RELEASE DATE,
GEN_NAME TEXT,
CONSTRAINT MOVIE_GENRE
	FOREIGN KEY (MOVIE_TITLE, YEAR_OF_RELEASE)
REFERENCES MOVIE (TITLE, YEAR_OF_RELEASE),
FOREIGN KEY (GEN_NAME)
REFERENCES GENRE (GEN_NAME)
);

CREATE TABLE PERSON (
PER_NAME TEXT,
BIRTH_DATE DATE,
PRIMARY KEY
(PER_NAME, BIRTH_DATE)
);

CREATE TABLE DIRECTED_BY (
MOVIE_TITLE TEXT,
YEAR_OF_RELEASE DATE,
DIR_NAME TEXT,
DIR_DATE DATE,
CONSTRAINT DIRECTED
	FOREIGN KEY (MOVIE_TITLE, YEAR_OF_RELEASE)
REFERENCES MOVIE (TITLE, YEAR_OF_RELEASE),
FOREIGN KEY (DIR_NAME, DIR_DATE)
REFERENCES PERSON (PER_NAME, BIRTH_DATE),
PRIMARY KEY
(MOVIE_TITLE, YEAR_OF_RELEASE, DIR_NAME, DIR_DATE)
);

CREATE TABLE HAS_AN_ACTOR (
MOVIE_TITLE TEXT,
YEAR_OF_RELEASE DATE,
ACT_NAME TEXT,
ACT_DATE DATE,
CONSTRAINT PLAY_ROLE
	FOREIGN KEY (MOVIE_TITLE, YEAR_OF_RELEASE)
REFERENCES MOVIE (TITLE, YEAR_OF_RELEASE),
FOREIGN KEY (ACT_NAME, ACT_DATE)
REFERENCES PERSON (PER_NAME, BIRTH_DATE),
PRIMARY KEY
(MOVIE_TITLE, YEAR_OF_RELEASE, ACT_NAME, ACT_DATE)
);

CREATE TABLE HAS_A_QUOTE_OF (
QUOTE_TXT TEXT,
MOVIE_TITLE TEXT,
YEAR_OF_RELEASE DATE,
ACT_NAME TEXT,
ACT_DATE DATE,
CONSTRAINT QUOTE_OF
	FOREIGN KEY (MOVIE_TITLE, YEAR_OF_RELEASE)
REFERENCES MOVIE (TITLE, YEAR_OF_RELEASE),
FOREIGN KEY (ACT_NAME, ACT_DATE)
REFERENCES PERSON (PER_NAME, BIRTH_DATE),
PRIMARY KEY
(MOVIE_TITLE, YEAR_OF_RELEASE, ACT_NAME, ACT_DATE)
);